spring:
  profiles:
    active: prod
project:
  domain: sturl.top
  goto-domain:
    white-list:
      enabled: true
      domains:
        - baidu.com
        - zhihu.com
        - bilibili.com
        - weibo.com